---
   - name: Install packages
     apt:
      name: "{{ item }}"
      state: present
     with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
     become: yes
   - name: Signing Key for Docker
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
   - name: Add Repostory
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
   - name: Install Docker
     apt:
      name: "{{ item }}"
      state: latest
     with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io
     become: yes
   - name: Add the user in Docker group
     user:
      name: ansible
      group: docker
      append: yes
   - name: Start the Docker Service
     service:
      name: docker
      state: restarted
      enabled: yes
     become: yes
